trigger:
- master

pool: "default"

jobs:
- job: FunctionBuild1
  displayName: 'Build Blob Function'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Project for Blob Function'
    inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)/BlobFunction/FunctionApp1/FunctionApp1.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build Blob Function' 
    inputs:
      command: 'build'
      projects: '$(Build.SourcesDirectory)/BlobFunction/FunctionApp1/FunctionApp1.csproj'
      arguments: '--configuration Release --output $(Build.BinariesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Blob Function' #Publication de la fonction Blob
    inputs:
      command: 'publish'
      projects: '$(Build.SourcesDirectory)/BlobFunction/FunctionApp1/FunctionApp1.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
      publishWebProjects: false

- job: FunctionDeploy1
  displayName: 'Deploy Blob Function'
  dependsOn: FunctionBuild1

  steps:
  - task: AzureFunctionApp@2
    displayName: 'Deploy Blob Function App'
    inputs:
      connectedServiceNameARM: 'Azure subscription 1(48795d1d-efc3-44f3-a40e-3565ec977a1a)'
      appName: 'BlobFunctionAppAzure'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      deployToSlotOrASE: false
      resourceGroupName: 'RG'
      slotName: 'production'
      appSettings: |
        Blob_ConnectionString: $(BlobConnectionString)
        ServiceBus_ConnectionString: $(AzureServiceBusConnectionString)
      appType: 'functionApp'

- job: FunctionBuild2
  displayName: 'Build Queue Function'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Project for Queue Function'
    inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)/QueueFunction/FunctionApp2/FunctionApp2.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build Queue Function'
    inputs:
      command: 'build'
      projects: '$(Build.SourcesDirectory)/QueueFunction/FunctionApp2/FunctionApp2.csproj'
      arguments: '--configuration Release --output $(Build.BinariesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Queue Function'
    inputs:
      command: 'publish'
      projects: '$(Build.SourcesDirectory)/QueueFunction/FunctionApp2/FunctionApp2.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

- job: FunctionDeploy2
  displayName: 'Deploy Queue Function'
  dependsOn: FunctionBuild2

  steps:
  - task: AzureFunctionApp@2
    displayName: 'Deploy Queue Function App'
    inputs:
      connectedServiceNameARM: 'Azure subscription 1(48795d1d-efc3-44f3-a40e-3565ec977a1a)'
      appName: 'queuefunctionappp'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      deployToSlotOrASE: false
      resourceGroupName: 'RG'
      slotName: 'production'
      appSettings: |
        Blob_ConnectionString: $(BlobConnectionString)
        ServiceBus_ConnectionString: $(AzureServiceBusConnectionString)
      appType: 'functionApp'
